// clubs-data.js — All Life Time club locations
// Source: my.lifetime.life/view-all-clubs.html
// Excludes: "Arriving", "Life Time Work", "Life Time Living", "Life Time Swim" entries
// Regions: Canada, USA-Northeast, USA-South, USA-Midwest, USA-West

const CLUBS_DATA = {
  "Canada": {
    "ajax":          { name: "Ajax",          state: "ON", url: "https://my.lifetime.life/clubs/on/ajax.html" },
    "barrie":        { name: "Barrie",        state: "ON", url: "https://my.lifetime.life/clubs/on/barrie.html" },
    "etobicoke":     { name: "Etobicoke",     state: "ON", url: "https://my.lifetime.life/clubs/on/etobicoke.html" },
    "kanata":        { name: "Kanata",        state: "ON", url: "https://my.lifetime.life/clubs/on/kanata.html" },
    "mississauga":   { name: "Mississauga",   state: "ON", url: "https://my.lifetime.life/clubs/on/mississauga.html" },
    "oakville":      { name: "Oakville",      state: "ON", url: "https://my.lifetime.life/clubs/on/oakville.html" },
    "ottawa":        { name: "Ottawa",        state: "ON", url: "https://my.lifetime.life/clubs/on/ottawa.html" },
    "richmond-hill": { name: "Richmond Hill", state: "ON", url: "https://my.lifetime.life/clubs/on/richmond-hill.html" },
    "scarborough":   { name: "Scarborough",   state: "ON", url: "https://my.lifetime.life/clubs/on/scarborough.html" },
    "toronto":       { name: "Toronto",       state: "ON", url: "https://my.lifetime.life/clubs/on/toronto.html" },
    "woodbridge":    { name: "Woodbridge",    state: "ON", url: "https://my.lifetime.life/clubs/on/woodbridge.html" }
  },
  "USA-Northeast": {
    "stamford-downtown":       { name: "Stamford Downtown",       state: "CT", url: "https://my.lifetime.life/clubs/ct/stamford-downtown.html" },
    "annapolis":               { name: "Annapolis",               state: "MD", url: "https://my.lifetime.life/clubs/md/annapolis.html" },
    "columbia":                { name: "Columbia",                state: "MD", url: "https://my.lifetime.life/clubs/md/columbia.html" },
    "gaithersburg":            { name: "Gaithersburg",            state: "MD", url: "https://my.lifetime.life/clubs/md/gaithersburg.html" },
    "potomac":                 { name: "Potomac",                 state: "MD", url: "https://my.lifetime.life/clubs/md/potomac.html" },
    "burlington":              { name: "Burlington",              state: "MA", url: "https://my.lifetime.life/clubs/ma/burlington.html" },
    "chestnut-hill":           { name: "Chestnut Hill",           state: "MA", url: "https://my.lifetime.life/clubs/ma/chestnut-hill.html" },
    "medford-at-station-landing": { name: "Medford at Station Landing", state: "MA", url: "https://my.lifetime.life/clubs/ma/medford-at-station-landing.html" },
    "metrowest-boston":        { name: "MetroWest-Boston",        state: "MA", url: "https://my.lifetime.life/clubs/ma/metrowest-boston.html" },
    "northshore":              { name: "Northshore",              state: "MA", url: "https://my.lifetime.life/clubs/ma/northshore.html" },
    "prudential-center":       { name: "Prudential Center",       state: "MA", url: "https://my.lifetime.life/clubs/ma/prudential-center.html" },
    "westwood":                { name: "Westwood",                state: "MA", url: "https://my.lifetime.life/clubs/ma/westwood.html" },
    "bergen-county":           { name: "Bergen County",           state: "NJ", url: "https://my.lifetime.life/clubs/nj/bergen-county.html" },
    "berkeley-heights":        { name: "Berkeley Heights",        state: "NJ", url: "https://my.lifetime.life/clubs/nj/berkeley-heights.html" },
    "bridgewater":             { name: "Bridgewater",             state: "NJ", url: "https://my.lifetime.life/clubs/nj/bridgewater.html" },
    "florham-park":            { name: "Florham Park",            state: "NJ", url: "https://my.lifetime.life/clubs/nj/florham-park.html" },
    "middletown-red-bank":     { name: "Middletown - Red Bank",   state: "NJ", url: "https://my.lifetime.life/clubs/nj/middletown-red-bank.html" },
    "mount-laurel":            { name: "Mount Laurel",            state: "NJ", url: "https://my.lifetime.life/clubs/nj/mount-laurel.html" },
    "princeton":               { name: "Princeton",               state: "NJ", url: "https://my.lifetime.life/clubs/nj/princeton.html" },
    "23rd-street":             { name: "23rd Street",             state: "NY", url: "https://my.lifetime.life/clubs/ny/23rd-street.html" },
    "atlantic-avenue":         { name: "Atlantic Avenue",         state: "NY", url: "https://my.lifetime.life/clubs/ny/atlantic-avenue.html" },
    "battery-park":            { name: "Battery Park",            state: "NY", url: "https://my.lifetime.life/clubs/ny/battery-park.html" },
    "chappaqua":               { name: "Chappaqua",               state: "NY", url: "https://my.lifetime.life/clubs/ny/chappaqua.html" },
    "dumbo":                   { name: "Dumbo",                   state: "NY", url: "https://my.lifetime.life/clubs/ny/dumbo.html" },
    "fifth-avenue":            { name: "Fifth Avenue",            state: "NY", url: "https://my.lifetime.life/clubs/ny/fifth-avenue.html" },
    "garden-city":             { name: "Garden City",             state: "NY", url: "https://my.lifetime.life/clubs/ny/garden-city.html" },
    "midtown":                 { name: "Midtown",                 state: "NY", url: "https://my.lifetime.life/clubs/ny/midtown.html" },
    "noho":                    { name: "NoHo",                    state: "NY", url: "https://my.lifetime.life/clubs/ny/noho.html" },
    "one-wall-street":         { name: "One Wall Street",         state: "NY", url: "https://my.lifetime.life/clubs/ny/one-wall-street.html" },
    "penn-1":                  { name: "PENN 1",                  state: "NY", url: "https://my.lifetime.life/clubs/ny/penn-1.html" },
    "sky-manhattan":           { name: "Sky (Manhattan)",         state: "NY", url: "https://my.lifetime.life/clubs/ny/sky-manhattan.html" },
    "syosset":                 { name: "Syosset",                 state: "NY", url: "https://my.lifetime.life/clubs/ny/syosset.html" },
    "westchester":             { name: "Westchester",             state: "NY", url: "https://my.lifetime.life/clubs/ny/westchester.html" },
    "ardmore":                 { name: "Ardmore",                 state: "PA", url: "https://my.lifetime.life/clubs/pa/ardmore.html" },
    "fort-washington":         { name: "Fort Washington",         state: "PA", url: "https://my.lifetime.life/clubs/pa/fort-washington.html" },
    "king-of-prussia":         { name: "King of Prussia",         state: "PA", url: "https://my.lifetime.life/clubs/pa/king-of-prussia.html" }
  },
  "USA-South": {
    "vestavia-hills":          { name: "Vestavia Hills",          state: "AL", url: "https://my.lifetime.life/clubs/al/vestavia-hills.html" },
    "boca-raton":              { name: "Boca Raton",              state: "FL", url: "https://my.lifetime.life/clubs/fl/boca-raton.html" },
    "coral-gables":            { name: "Coral Gables",            state: "FL", url: "https://my.lifetime.life/clubs/fl/coral-gables.html" },
    "harbour-island":          { name: "Harbour Island",          state: "FL", url: "https://my.lifetime.life/clubs/fl/harbour-island.html" },
    "miami-at-the-falls":      { name: "Miami at The Falls",      state: "FL", url: "https://my.lifetime.life/clubs/fl/miami-at-the-falls.html" },
    "palm-beach-gardens":      { name: "Palm Beach Gardens",      state: "FL", url: "https://my.lifetime.life/clubs/fl/palm-beach-gardens.html" },
    "west-boca":               { name: "West Boca",               state: "FL", url: "https://my.lifetime.life/clubs/fl/west-boca.html" },
    "winter-park":             { name: "Winter Park",             state: "FL", url: "https://my.lifetime.life/clubs/fl/winter-park.html" },
    "alpharetta":              { name: "Alpharetta",              state: "GA", url: "https://my.lifetime.life/clubs/ga/alpharetta.html" },
    "buckhead-at-phipps-plaza":{ name: "Buckhead at Phipps Plaza",state: "GA", url: "https://my.lifetime.life/clubs/ga/buckhead-at-phipps-plaza.html" },
    "johns-creek":             { name: "Johns Creek",             state: "GA", url: "https://my.lifetime.life/clubs/ga/johns-creek.html" },
    "north-druid-hills":       { name: "North Druid Hills",       state: "GA", url: "https://my.lifetime.life/clubs/ga/north-druid-hills.html" },
    "peachtree-corners":       { name: "Peachtree Corners",       state: "GA", url: "https://my.lifetime.life/clubs/ga/peachtree-corners.html" },
    "perimeter":               { name: "Perimeter",               state: "GA", url: "https://my.lifetime.life/clubs/ga/perimeter.html" },
    "sandy-springs":           { name: "Sandy Springs",           state: "GA", url: "https://my.lifetime.life/clubs/ga/sandy-springs.html" },
    "sugarloaf":               { name: "Sugarloaf",               state: "GA", url: "https://my.lifetime.life/clubs/ga/sugarloaf.html" },
    "woodstock":               { name: "Woodstock",               state: "GA", url: "https://my.lifetime.life/clubs/ga/woodstock.html" },
    "alston-town-center":      { name: "Alston Town Center",      state: "NC", url: "https://my.lifetime.life/clubs/nc/alston-town-center.html" },
    "apex":                    { name: "Apex",                    state: "NC", url: "https://my.lifetime.life/clubs/nc/apex.html" },
    "cary":                    { name: "Cary",                    state: "NC", url: "https://my.lifetime.life/clubs/nc/cary.html" },
    "charlotte":               { name: "Charlotte",               state: "NC", url: "https://my.lifetime.life/clubs/nc/charlotte.html" },
    "raleigh":                 { name: "Raleigh",                 state: "NC", url: "https://my.lifetime.life/clubs/nc/raleigh.html" },
    "oklahoma-city":           { name: "Oklahoma City",           state: "OK", url: "https://my.lifetime.life/clubs/ok/oklahoma-city.html" },
    "south-tulsa":             { name: "South Tulsa",             state: "OK", url: "https://my.lifetime.life/clubs/ok/south-tulsa.html" },
    "collierville":            { name: "Collierville",            state: "TN", url: "https://my.lifetime.life/clubs/tn/collierville.html" },
    "franklin":                { name: "Franklin",                state: "TN", url: "https://my.lifetime.life/clubs/tn/franklin.html" },
    "allen":                   { name: "Allen",                   state: "TX", url: "https://my.lifetime.life/clubs/tx/allen.html" },
    "austin-arboretum":        { name: "Austin - Arboretum",      state: "TX", url: "https://my.lifetime.life/clubs/tx/austin-arboretum.html" },
    "austin-downtown":         { name: "Austin - Downtown",       state: "TX", url: "https://my.lifetime.life/clubs/tx/austin-downtown.html" },
    "austin-north":            { name: "Austin - North",          state: "TX", url: "https://my.lifetime.life/clubs/tx/austin-north.html" },
    "austin-south":            { name: "Austin - South",          state: "TX", url: "https://my.lifetime.life/clubs/tx/austin-south.html" },
    "baybrook":                { name: "Baybrook",                state: "TX", url: "https://my.lifetime.life/clubs/tx/baybrook.html" },
    "champions":               { name: "Champions",               state: "TX", url: "https://my.lifetime.life/clubs/tx/champions.html" },
    "cinco-ranch":             { name: "Cinco Ranch",             state: "TX", url: "https://my.lifetime.life/clubs/tx/cinco-ranch.html" },
    "city-centre-houston":     { name: "City Centre Houston",     state: "TX", url: "https://my.lifetime.life/clubs/tx/city-centre-houston.html" },
    "colleyville":             { name: "Colleyville",             state: "TX", url: "https://my.lifetime.life/clubs/tx/colleyville.html" },
    "cypress":                 { name: "Cypress",                 state: "TX", url: "https://my.lifetime.life/clubs/tx/cypress.html" },
    "dallas-addison":          { name: "Dallas - Addison",        state: "TX", url: "https://my.lifetime.life/clubs/tx/dallas-addison.html" },
    "dallas-highland-park":    { name: "Dallas - Highland Park",  state: "TX", url: "https://my.lifetime.life/clubs/tx/dallas-highland-park.html" },
    "flower-mound":            { name: "Flower Mound",            state: "TX", url: "https://my.lifetime.life/clubs/tx/flower-mound.html" },
    "fort-worth-alliance":     { name: "Fort Worth-Alliance",     state: "TX", url: "https://my.lifetime.life/clubs/tx/fort-worth-alliance.html" },
    "frisco":                  { name: "Frisco",                  state: "TX", url: "https://my.lifetime.life/clubs/tx/frisco.html" },
    "garland":                 { name: "Garland",                 state: "TX", url: "https://my.lifetime.life/clubs/tx/garland.html" },
    "greenstreet":             { name: "GreenStreet",             state: "TX", url: "https://my.lifetime.life/clubs/tx/greenstreet.html" },
    "greenway":                { name: "Greenway",                state: "TX", url: "https://my.lifetime.life/clubs/tx/greenway.html" },
    "kingwood":                { name: "Kingwood",                state: "TX", url: "https://my.lifetime.life/clubs/tx/kingwood.html" },
    "lake-houston":            { name: "Lake Houston",            state: "TX", url: "https://my.lifetime.life/clubs/tx/lake-houston.html" },
    "las-colinas":             { name: "Las Colinas",             state: "TX", url: "https://my.lifetime.life/clubs/tx/las-colinas.html" },
    "mansfield":               { name: "Mansfield",               state: "TX", url: "https://my.lifetime.life/clubs/tx/mansfield.html" },
    "mckinney-at-craig-ranch": { name: "McKinney at Craig Ranch", state: "TX", url: "https://my.lifetime.life/clubs/tx/mckinney-at-craig-ranch.html" },
    "missouri-city":           { name: "Missouri City",           state: "TX", url: "https://my.lifetime.life/clubs/tx/missouri-city.html" },
    "plano":                   { name: "Plano",                   state: "TX", url: "https://my.lifetime.life/clubs/tx/plano.html" },
    "san-antonio-281":         { name: "San Antonio 281",         state: "TX", url: "https://my.lifetime.life/clubs/tx/san-antonio-281.html" },
    "san-antonio-at-the-rim":  { name: "San Antonio at the Rim",  state: "TX", url: "https://my.lifetime.life/clubs/tx/san-antonio-at-the-rim.html" },
    "shenandoah":              { name: "Shenandoah",              state: "TX", url: "https://my.lifetime.life/clubs/tx/shenandoah.html" },
    "south-lamar":             { name: "South Lamar",             state: "TX", url: "https://my.lifetime.life/clubs/tx/south-lamar.html" },
    "sugar-land":              { name: "Sugar Land",              state: "TX", url: "https://my.lifetime.life/clubs/tx/sugar-land.html" },
    "westlake":                { name: "Westlake",                state: "TX", url: "https://my.lifetime.life/clubs/tx/westlake.html" }
  },
  "USA-Midwest": {
    "algonquin":               { name: "Algonquin",               state: "IL", url: "https://my.lifetime.life/clubs/il/algonquin.html" },
    "bloomingdale":            { name: "Bloomingdale",            state: "IL", url: "https://my.lifetime.life/clubs/il/bloomingdale.html" },
    "burr-ridge":              { name: "Burr Ridge",              state: "IL", url: "https://my.lifetime.life/clubs/il/burr-ridge.html" },
    "burr-ridge-sport-and-racquet": { name: "Burr Ridge Sport and Racquet", state: "IL", url: "https://my.lifetime.life/clubs/il/burr-ridge-sport-and-racquet.html" },
    "evanston":                { name: "Evanston",                state: "IL", url: "https://my.lifetime.life/clubs/il/evanston.html" },
    "lake-zurich":             { name: "Lake Zurich",             state: "IL", url: "https://my.lifetime.life/clubs/il/lake-zurich.html" },
    "northbrook":              { name: "Northbrook",              state: "IL", url: "https://my.lifetime.life/clubs/il/northbrook.html" },
    "oakbrook":                { name: "Oakbrook",                state: "IL", url: "https://my.lifetime.life/clubs/il/oakbrook.html" },
    "old-orchard":             { name: "Old Orchard",             state: "IL", url: "https://my.lifetime.life/clubs/il/old-orchard.html" },
    "orland-park":             { name: "Orland Park",             state: "IL", url: "https://my.lifetime.life/clubs/il/orland-park.html" },
    "river-north-at-one-chicago": { name: "River North at One Chicago", state: "IL", url: "https://my.lifetime.life/clubs/il/river-north-at-one-chicago.html" },
    "romeoville":              { name: "Romeoville",              state: "IL", url: "https://my.lifetime.life/clubs/il/romeoville.html" },
    "schaumburg":              { name: "Schaumburg",              state: "IL", url: "https://my.lifetime.life/clubs/il/schaumburg.html" },
    "vernon-hills":            { name: "Vernon Hills",            state: "IL", url: "https://my.lifetime.life/clubs/il/vernon-hills.html" },
    "warrenville":             { name: "Warrenville",             state: "IL", url: "https://my.lifetime.life/clubs/il/warrenville.html" },
    "castle-creek":            { name: "Castle Creek",            state: "IN", url: "https://my.lifetime.life/clubs/in/castle-creek.html" },
    "fishers":                 { name: "Fishers",                 state: "IN", url: "https://my.lifetime.life/clubs/in/fishers.html" },
    "des-moines":              { name: "Des Moines",              state: "IA", url: "https://my.lifetime.life/clubs/ia/des-moines.html" },
    "lenexa":                  { name: "Lenexa",                  state: "KS", url: "https://my.lifetime.life/clubs/ks/lenexa.html" },
    "overland-park":           { name: "Overland Park",           state: "KS", url: "https://my.lifetime.life/clubs/ks/overland-park.html" },
    "bloomfield-township":     { name: "Bloomfield Township",     state: "MI", url: "https://my.lifetime.life/clubs/mi/bloomfield-township.html" },
    "canton-township":         { name: "Canton Township",         state: "MI", url: "https://my.lifetime.life/clubs/mi/canton-township.html" },
    "commerce-township":       { name: "Commerce Township",       state: "MI", url: "https://my.lifetime.life/clubs/mi/commerce-township.html" },
    "novi":                    { name: "Novi",                    state: "MI", url: "https://my.lifetime.life/clubs/mi/novi.html" },
    "rochester-hills":         { name: "Rochester Hills",         state: "MI", url: "https://my.lifetime.life/clubs/mi/rochester-hills.html" },
    "shelby-township":         { name: "Shelby Township",         state: "MI", url: "https://my.lifetime.life/clubs/mi/shelby-township.html" },
    "troy":                    { name: "Troy",                    state: "MI", url: "https://my.lifetime.life/clubs/mi/troy.html" },
    "apple-valley":            { name: "Apple Valley",            state: "MN", url: "https://my.lifetime.life/clubs/mn/apple-valley.html" },
    "bloomington-north":       { name: "Bloomington North",       state: "MN", url: "https://my.lifetime.life/clubs/mn/bloomington-north.html" },
    "bloomington-south":       { name: "Bloomington South",       state: "MN", url: "https://my.lifetime.life/clubs/mn/bloomington-south.html" },
    "champlin":                { name: "Champlin",                state: "MN", url: "https://my.lifetime.life/clubs/mn/champlin.html" },
    "chanhassen":              { name: "Chanhassen",              state: "MN", url: "https://my.lifetime.life/clubs/mn/chanhassen.html" },
    "coon-rapids":             { name: "Coon Rapids",             state: "MN", url: "https://my.lifetime.life/clubs/mn/coon-rapids.html" },
    "crosstown-eden-prairie":  { name: "Crosstown (Eden Prairie)",state: "MN", url: "https://my.lifetime.life/clubs/mn/crosstown-eden-prairie.html" },
    "eagan":                   { name: "Eagan",                   state: "MN", url: "https://my.lifetime.life/clubs/mn/eagan.html" },
    "eden-prairie-athletic":   { name: "Eden Prairie Athletic",   state: "MN", url: "https://my.lifetime.life/clubs/mn/eden-prairie-athletic.html" },
    "edina-at-southdale":      { name: "Edina at Southdale",      state: "MN", url: "https://my.lifetime.life/clubs/mn/edina-at-southdale.html" },
    "fridley":                 { name: "Fridley",                 state: "MN", url: "https://my.lifetime.life/clubs/mn/fridley.html" },
    "highland-park":           { name: "Highland Park",           state: "MN", url: "https://my.lifetime.life/clubs/mn/highland-park.html" },
    "lakeville":               { name: "Lakeville",               state: "MN", url: "https://my.lifetime.life/clubs/mn/lakeville.html" },
    "maple-grove":             { name: "Maple Grove",             state: "MN", url: "https://my.lifetime.life/clubs/mn/maple-grove.html" },
    "minnetonka":              { name: "Minnetonka",              state: "MN", url: "https://my.lifetime.life/clubs/mn/minnetonka.html" },
    "new-hope":                { name: "New Hope",                state: "MN", url: "https://my.lifetime.life/clubs/mn/new-hope.html" },
    "plymouth":                { name: "Plymouth",                state: "MN", url: "https://my.lifetime.life/clubs/mn/plymouth.html" },
    "rosemount":               { name: "Rosemount",               state: "MN", url: "https://my.lifetime.life/clubs/mn/rosemount.html" },
    "savage":                  { name: "Savage",                  state: "MN", url: "https://my.lifetime.life/clubs/mn/savage.html" },
    "st-louis-park":           { name: "St. Louis Park",          state: "MN", url: "https://my.lifetime.life/clubs/mn/st-louis-park.html" },
    "target-center-minneapolis":{ name: "Target Center (Minneapolis)", state: "MN", url: "https://my.lifetime.life/clubs/mn/target-center-minneapolis.html" },
    "white-bear-lake":         { name: "White Bear Lake",         state: "MN", url: "https://my.lifetime.life/clubs/mn/white-bear-lake.html" },
    "woodbury":                { name: "Woodbury",                state: "MN", url: "https://my.lifetime.life/clubs/mn/woodbury.html" },
    "creve-coeur":             { name: "Creve Coeur",             state: "MO", url: "https://my.lifetime.life/clubs/mo/creve-coeur.html" },
    "frontenac":               { name: "Frontenac",               state: "MO", url: "https://my.lifetime.life/clubs/mo/frontenac.html" },
    "west-county-chesterfield":{ name: "West County-Chesterfield",state: "MO", url: "https://my.lifetime.life/clubs/mo/west-county-chesterfield.html" },
    "omaha":                   { name: "Omaha",                   state: "NE", url: "https://my.lifetime.life/clubs/ne/omaha.html" },
    "beachwood":               { name: "Beachwood",               state: "OH", url: "https://my.lifetime.life/clubs/oh/beachwood.html" },
    "deerfield-township":      { name: "Deerfield Township",      state: "OH", url: "https://my.lifetime.life/clubs/oh/deerfield-township.html" },
    "dublin":                  { name: "Dublin",                  state: "OH", url: "https://my.lifetime.life/clubs/oh/dublin.html" },
    "easton":                  { name: "Easton",                  state: "OH", url: "https://my.lifetime.life/clubs/oh/easton.html" },
    "eastside-sport-and-racquet": { name: "Eastside Sport and Racquet", state: "OH", url: "https://my.lifetime.life/clubs/oh/eastside-sport-and-racquet.html" },
    "pickerington":            { name: "Pickerington",            state: "OH", url: "https://my.lifetime.life/clubs/oh/pickerington.html" },
    "upper-arlington":         { name: "Upper Arlington",         state: "OH", url: "https://my.lifetime.life/clubs/oh/upper-arlington.html" },
    "brookfield":              { name: "Brookfield",              state: "WI", url: "https://my.lifetime.life/clubs/wi/brookfield.html" }
  },
  "USA-West": {
    "biltmore":                { name: "Biltmore",                state: "AZ", url: "https://my.lifetime.life/clubs/az/biltmore.html" },
    "gilbert":                 { name: "Gilbert",                 state: "AZ", url: "https://my.lifetime.life/clubs/az/gilbert.html" },
    "happy-valley-peoria":     { name: "Happy Valley-Peoria",     state: "AZ", url: "https://my.lifetime.life/clubs/az/happy-valley-peoria.html" },
    "north-scottsdale":        { name: "North Scottsdale",        state: "AZ", url: "https://my.lifetime.life/clubs/az/north-scottsdale.html" },
    "ocotillo":                { name: "Ocotillo",                state: "AZ", url: "https://my.lifetime.life/clubs/az/ocotillo.html" },
    "palm-valley":             { name: "Palm Valley",             state: "AZ", url: "https://my.lifetime.life/clubs/az/palm-valley.html" },
    "paradise-valley":         { name: "Paradise Valley",         state: "AZ", url: "https://my.lifetime.life/clubs/az/paradise-valley.html" },
    "scottsdale-fashion-square":{ name: "Scottsdale Fashion Square", state: "AZ", url: "https://my.lifetime.life/clubs/az/scottsdale-fashion-square.html" },
    "tempe":                   { name: "Tempe",                   state: "AZ", url: "https://my.lifetime.life/clubs/az/tempe.html" },
    "arden":                   { name: "Arden",                   state: "CA", url: "https://my.lifetime.life/clubs/ca/arden.html" },
    "folsom":                  { name: "Folsom",                  state: "CA", url: "https://my.lifetime.life/clubs/ca/folsom.html" },
    "la-jolla":                { name: "La Jolla",                state: "CA", url: "https://my.lifetime.life/clubs/ca/la-jolla.html" },
    "laguna-niguel":           { name: "Laguna Niguel",           state: "CA", url: "https://my.lifetime.life/clubs/ca/laguna-niguel.html" },
    "lakeshore-irvine":        { name: "Lakeshore-Irvine",        state: "CA", url: "https://my.lifetime.life/clubs/ca/lakeshore-irvine.html" },
    "otay-ranch":              { name: "Otay Ranch",              state: "CA", url: "https://my.lifetime.life/clubs/ca/otay-ranch.html" },
    "rancho-san-clemente":     { name: "Rancho San Clemente",     state: "CA", url: "https://my.lifetime.life/clubs/ca/rancho-san-clemente.html" },
    "roseville":               { name: "Roseville",               state: "CA", url: "https://my.lifetime.life/clubs/ca/roseville.html" },
    "walnut-creek":            { name: "Walnut Creek",            state: "CA", url: "https://my.lifetime.life/clubs/ca/walnut-creek.html" },
    "boulder":                 { name: "Boulder",                 state: "CO", url: "https://my.lifetime.life/clubs/co/boulder.html" },
    "centennial":              { name: "Centennial",              state: "CO", url: "https://my.lifetime.life/clubs/co/centennial.html" },
    "centennial-tennis":       { name: "Centennial Tennis",       state: "CO", url: "https://my.lifetime.life/clubs/co/centennial-tennis.html" },
    "cherry-creek":            { name: "Cherry Creek",            state: "CO", url: "https://my.lifetime.life/clubs/co/cherry-creek.html" },
    "colorado-springs":        { name: "Colorado Springs",        state: "CO", url: "https://my.lifetime.life/clubs/co/colorado-springs.html" },
    "denver-west":             { name: "Denver West",             state: "CO", url: "https://my.lifetime.life/clubs/co/denver-west.html" },
    "flatirons":               { name: "Flatirons",               state: "CO", url: "https://my.lifetime.life/clubs/co/flatirons.html" },
    "parker-aurora":           { name: "Parker-Aurora",           state: "CO", url: "https://my.lifetime.life/clubs/co/parker-aurora.html" },
    "westminster":             { name: "Westminster",             state: "CO", url: "https://my.lifetime.life/clubs/co/westminster.html" },
    "eagle":                   { name: "Eagle",                   state: "ID", url: "https://my.lifetime.life/clubs/id/eagle.html" },
    "green-valley":            { name: "Green Valley",            state: "NV", url: "https://my.lifetime.life/clubs/nv/green-valley.html" },
    "summerlin":               { name: "Summerlin",               state: "NV", url: "https://my.lifetime.life/clubs/nv/summerlin.html" },
    "beaverton":               { name: "Beaverton",               state: "OR", url: "https://my.lifetime.life/clubs/or/beaverton.html" },
    "south-jordan":            { name: "South Jordan",            state: "UT", url: "https://my.lifetime.life/clubs/ut/south-jordan.html" },
    "bellevue":                { name: "Bellevue",                state: "WA", url: "https://my.lifetime.life/clubs/wa/bellevue.html" }
  }
};

if (typeof module !== 'undefined') module.exports = CLUBS_DATA;