// scheduler.js
// Generates RunBooking.bat and RegisterTask.bat content from wizard config.
// Called by exporter.js at export time.

/**
 * Generates the RunBooking.bat content that auto-imports the macro then runs it.
 * @param {string} macroName - The filename without extension, e.g. "BookingTemplate"
 * @returns {string} bat file content
 */
function generateRunBookingBat(macroName) {
  return `@echo off
REM ============================================================
REM  RunBooking.bat — Auto-imports and launches UIVision macro
REM  Generated by Life Time Booking Wizard
REM  DO NOT EDIT unless you know what you're doing.
REM ============================================================

SET MACRO_NAME=${macroName}
SET MACRO_FILE=%~dp0${macroName}.json
SET CHROME_PATH=

REM Try default Chrome install locations
IF EXIST "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" (
  SET CHROME_PATH=C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe
)
IF EXIST "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" (
  SET CHROME_PATH=C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe
)

IF "%CHROME_PATH%"=="" (
  echo ERROR: Chrome not found. Please install Google Chrome.
  pause
  exit /b 1
)

IF NOT EXIST "%MACRO_FILE%" (
  echo ERROR: Macro file not found: %MACRO_FILE%
  echo Make sure ${macroName}.json is in the same folder as this bat file.
  pause
  exit /b 1
)

REM Step 1 — Import the macro into UIVision from the local JSON file
echo Importing macro: %MACRO_NAME%
start "" "%CHROME_PATH%" "chrome-extension://gcbalfbdmfieckjlnblleoemohcganoc/popup.html?importmacro=%MACRO_FILE%"

REM Wait for import to complete before launching
timeout /t 5 /nobreak >nul

REM Step 2 — Run the macro
echo Running macro: %MACRO_NAME%
start "" "%CHROME_PATH%" "chrome-extension://gcbalfbdmfieckjlnblleoemohcganoc/popup.html?direct=1&macro=%MACRO_NAME%&close=1&closeRPA=0"

exit /b 0
`;
}

/**
 * Calculates the booking window open date (classDate minus daysAhead).
 * Returns MM/DD/YYYY for schtasks compatibility.
 * @param {number} daysAhead
 * @param {string|null} classDate - YYYY-MM-DD from wizard
 * @returns {string} MM/DD/YYYY
 */
function calcScheduleDate(daysAhead, classDate) {
  let d;
  if (classDate) {
    const [yyyy, mm, dd] = classDate.split('-').map(Number);
    d = new Date(yyyy, mm - 1, dd);     // local midnight — no UTC shift
    d.setDate(d.getDate() - daysAhead); // go back daysAhead days
  } else {
    d = new Date(); // fallback: today
  }
  const mo  = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  const yr  = d.getFullYear();
  return `${mo}/${day}/${yr}`;
}

/**
 * Returns the day-of-week name from a YYYY-MM-DD date string.
 * Uses local date constructor to avoid UTC timezone shifting.
 * e.g. "2026-06-03" → "Wednesday"
 * @param {string|null} classDate
 * @returns {string}
 */
function getDayOfWeek(classDate) {
  if (!classDate) return 'Monday';
  const [yyyy, mm, dd] = classDate.split('-').map(Number);
  const days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
  return days[new Date(yyyy, mm - 1, dd).getDay()];
}

/**
 * Parses a time string like "9:00 AM" or "09:00" into 24-hour HH:MM.
 * @param {string} timeStr
 * @returns {string} HH:MM
 */
function parseTo24Hour(timeStr) {
  const clean = timeStr.trim().toUpperCase();
  const ampm  = clean.includes('AM') ? 'AM' : clean.includes('PM') ? 'PM' : null;
  const parts = clean.replace('AM', '').replace('PM', '').trim().split(':');
  let hours   = parseInt(parts[0], 10);
  const mins  = parts[1] ? parts[1].padStart(2, '0') : '00';
  if (ampm === 'PM' && hours !== 12) hours += 12;
  if (ampm === 'AM' && hours === 12) hours = 0;
  return `${String(hours).padStart(2, '0')}:${mins}`;
}

/**
 * Generates RegisterTask.bat — registers a weekly Windows Scheduled Task
 * AND configures all required system settings automatically.
 * User right-clicks and runs as Administrator once.
 * @param {object} config - wizard state.config or state.config.schedule
 * @param {string} macroName - e.g. "BookingTemplate"
 * @returns {string} bat file content
 */
function generateRegisterTaskBat(config, macroName) {
  const classDate  = config.classDate  || (config.schedule && config.schedule.classDate)  || null;
  const daysAhead  = Number(config.daysAhead  || (config.schedule && config.schedule.daysAhead)  || 7);
  const runTime24  = config.runTime  || (config.schedule && config.schedule.runTime)  || '09:00';

  const schedDate     = calcScheduleDate(daysAhead, classDate);
  const taskName      = `LifeTimeBooking_${macroName.replace(/\s+/g, '_')}`;
  const [mo, day, yr] = schedDate.split('/');
  const isoDateTime   = `${yr}-${mo}-${day}T${runTime24}:00`;
  const dayOfWeek     = getDayOfWeek(classDate);

  return `@echo off
REM ============================================================
REM  RegisterTask.bat — System Setup + Weekly Scheduled Task
REM  RIGHT-CLICK and select "Run as administrator"
REM  You only need to do this ONCE.
REM ============================================================

SET TASK_NAME=${taskName}
SET BAT_PATH=%~dp0RunBooking.bat
SET XML_PATH=%~dp0task.xml

echo(
echo ============================================================
echo  STEP 1 — Configuring system settings for reliable automation
echo ============================================================
echo(

REM Enable wake timers on AC power and battery
powercfg /setacvalueindex SCHEME_CURRENT SUB_SLEEP RTCWAKE 1
powercfg /setdcvalueindex SCHEME_CURRENT SUB_SLEEP RTCWAKE 1
powercfg /setactive SCHEME_CURRENT
echo [OK] Wake timers enabled

REM Set sleep timeout to 30 minutes so PC stays awake during macro
powercfg /change standby-timeout-ac 30
powercfg /change standby-timeout-dc 30
echo [OK] Sleep timeout set to 30 minutes minimum

REM Disable fast startup (can interfere with scheduled wake)
reg add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Power" /v HiberbootEnabled /t REG_DWORD /d 0 /f >nul 2>&1
echo [OK] Fast startup disabled

REM Allow UIVision extension to access local file URLs
reg add "HKLM\\SOFTWARE\\Policies\\Google\\Chrome\\ExtensionSettings\\gcbalfbdmfieckjlnblleoemohcganoc" /v "file_url_navigation_allowed" /t REG_DWORD /d 1 /f >nul 2>&1
echo [OK] UIVision file access configured

REM Check if UIVision storage folder exists (confirms UIVision is installed)
SET UIVISION_DIR=%USERPROFILE%\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\File System
IF EXIST "%UIVISION_DIR%" (
  echo [OK] UIVision installation detected
) ELSE (
  echo [!!] WARNING: UIVision folder not found.
  echo      Make sure UIVision is installed in Chrome before running the macro.
  echo      Install from: https://chrome.google.com/webstore/detail/uivision/gcbalfbdmfieckjlnblleoemohcganoc
)

REM Warn if domain-joined (corporate PCs may force screen lock)
for /f "tokens=2 delims==" %%a in ('wmic computersystem get partofdomain /value 2^>nul') do set DOMAIN=%%a
if /i "%DOMAIN%"=="TRUE" (
  echo(
  echo [!!] WARNING: This PC is joined to a corporate domain.
  echo      Your IT policy may lock the screen and block the macro.
  echo      Contact your IT department if bookings fail silently.
)

echo(
echo ============================================================
echo  STEP 2 — Registering weekly scheduled task
echo ============================================================
echo(
echo Task name   : %TASK_NAME%
echo First run   : ${isoDateTime}
echo Repeats     : Every ${dayOfWeek} at ${runTime24}
echo Bat file    : %BAT_PATH%
echo(

REM Write the task XML file
(
echo ^<?xml version="1.0" encoding="UTF-16"?^>
echo ^<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task"^>
echo   ^<Triggers^>
echo     ^<CalendarTrigger^>
echo       ^<StartBoundary^>${isoDateTime}^</StartBoundary^>
echo       ^<Enabled^>true^</Enabled^>
echo       ^<ScheduleByWeek^>
echo         ^<WeeksInterval^>1^</WeeksInterval^>
echo         ^<DaysOfWeek^>
echo           ^<${dayOfWeek}/^>
echo         ^</DaysOfWeek^>
echo       ^</ScheduleByWeek^>
echo     ^</CalendarTrigger^>
echo   ^</Triggers^>
echo   ^<Settings^>
echo     ^<StartWhenAvailable^>true^</StartWhenAvailable^>
echo     ^<WakeToRun^>true^</WakeToRun^>
echo     ^<DisallowStartIfOnBatteries^>false^</DisallowStartIfOnBatteries^>
echo     ^<StopIfGoingOnBatteries^>false^</StopIfGoingOnBatteries^>
echo     ^<ExecutionTimeLimit^>PT1H^</ExecutionTimeLimit^>
echo     ^<MultipleInstancesPolicy^>IgnoreNew^</MultipleInstancesPolicy^>
echo   ^</Settings^>
echo   ^<Actions Context="Author"^>
echo     ^<Exec^>
echo       ^<Command^>"%BAT_PATH%"^</Command^>
echo     ^</Exec^>
echo   ^</Actions^>
echo   ^<Principals^>
echo     ^<Principal id="Author"^>
echo       ^<LogonType^>InteractiveToken^</LogonType^>
echo       ^<RunLevel^>HighestAvailable^</RunLevel^>
echo     ^</Principal^>
echo   ^</Principals^>
echo ^</Task^>
) > "%XML_PATH%"

schtasks /create /tn "%TASK_NAME%" /xml "%XML_PATH%" /f

IF %ERRORLEVEL% EQU 0 (
  echo(
  echo ============================================================
  echo  SUCCESS! Everything is configured and scheduled.
  echo ============================================================
  echo(
  echo Task      : %TASK_NAME%
  echo First run : ${isoDateTime}
  echo Repeats   : Every ${dayOfWeek} at ${runTime24}
  echo(
  echo To run RIGHT NOW for testing, double-click RunBooking.bat
  echo(
  echo IMPORTANT: PC must be ON or in SLEEP mode at booking time.
  echo            Hibernate and Shutdown will prevent the wake.
  echo(
  echo If wake-from-sleep does not work, check Windows power settings:
  echo   Settings - System - Power and Sleep - Additional power settings
  echo   Change plan settings - Change advanced power settings
  echo   Sleep - Allow wake timers - set to Enabled
) ELSE (
  echo(
  echo ERROR: Scheduled task could not be registered.
  echo Did you right-click and choose "Run as administrator"?
)

REM Clean up temp XML
IF EXIST "%XML_PATH%" DEL "%XML_PATH%"

echo(
pause
`;
}

/**
 * Generates a plain-English README_BOOKING.txt for non-techie users.
 * @param {object} config - wizard state.config or state.config.schedule
 * @param {string} macroName
 * @returns {string}
 */
function generateReadme(config, macroName) {
  const classDate = config.classDate || (config.schedule && config.schedule.classDate) || null;
  const daysAhead = Number(config.daysAhead || (config.schedule && config.schedule.daysAhead) || 7);
  const runTime24 = config.runTime || (config.schedule && config.schedule.runTime) || '09:00';
  const schedDate = calcScheduleDate(daysAhead, classDate);
  const dayOfWeek = getDayOfWeek(classDate);

  return `GYM CLASS AUTO-BOOKING — SETUP GUIDE
===================================================

What this does:
  This folder contains the files your Gym Booking Chrome plugin uses
  to automatically book your gym class every week. You set it up once
  and it runs on its own from then on. You don't need to be at your
  computer when it runs.

Files included in this folder:
  • ${macroName}.json    → Your booking configuration (do not rename or move)
  • RunBooking.bat       → Runs the booking right now (great for testing)
  • RegisterTask.bat     → Schedules the booking to run automatically every week
  • README_BOOKING.txt   → This file

  IMPORTANT: Keep all four files in the same folder at all times.
             Moving or renaming any of them will break the automation.


WHAT YOU NEED
-------------
  • A Windows PC (Windows 10 or 11) — this does not work on Mac
  • Google Chrome installed — not Edge, not Firefox, Chrome specifically


ONE-TIME SETUP (do this once, takes about 5 minutes)
-----------------------------------------------------

STEP 1 — Install UIVision in Chrome

  UIVision is the free Chrome extension that does the actual clicking
  and booking on your behalf. It's on the official Chrome Web Store
  and your credentials never leave your own computer.

  1. Open Google Chrome
  2. Go to: https://chrome.google.com/webstore/detail/uivision/gcbalfbdmfieckjlnblleoemohcganoc
  3. Click "Add to Chrome" then "Add extension" when prompted
  4. Click the puzzle piece icon in Chrome's top-right corner
  5. Click UIVision in the list, let it open, then close it again

  You only need to do this once.


STEP 2 — Install UIVision XModules

  XModules is a small free companion app that lets UIVision read your
  booking file from your hard drive. Without it, the booking will open
  Chrome but nothing will happen.

  1. Go to: https://ui.vision/rpa/x/download
  2. Click the Windows download link and run the installer
  3. Click through the installer — accept all defaults
  4. Once it finishes, open Chrome and click the UIVision icon
  5. Go to Settings → XModule Status
  6. You should see green checkmarks next to the modules

  You only need to do this once.


STEP 3 — Turn Off Screen Lock

  If your screen locks while the plugin is running, Chrome can't
  complete the booking. To prevent this:

  1. Open the Start menu and click Settings (the gear icon)
  2. Go to Accounts → Sign-in options
  3. Find "Require sign-in" and set it to Never

  Your PC will still sleep normally — this only stops it from
  locking you out when it wakes up.


STEP 4 — Run the Scheduler (one time only)

  This tells Windows to wake your PC and run the booking automatically
  every week.

  1. Right-click RegisterTask.bat
  2. Select "Run as administrator"
     (A blue pop-up may ask permission — click Yes)
  3. A black window will appear and scroll through setup steps
     — this is normal, don't close it
  4. Wait until you see:

       SUCCESS! Everything is configured and scheduled.

  5. Press any key to close the window.

  If you see ERROR instead, you likely need to right-click and choose
  "Run as administrator" again.


YOU'RE ALL SET
--------------
  Your booking is now scheduled to run automatically:

    First run : ${schedDate} at ${runTime24}
    Repeats   : Every ${dayOfWeek} at ${runTime24}

  As long as your PC is on or in sleep mode at that time, the plugin
  will wake it up, open Chrome, log in to Life Time, and book your spot.
  You'll get a booking confirmation email from Life Time as proof it worked.

  PC State at booking time:
    On (screen on or off)  = Will work      ✓
    Sleep mode             = Will work      ✓  (PC wakes itself up)
    Hibernate              = Will NOT work  ✗
    Shut down              = Will NOT work  ✗

  Tip: Leave your PC plugged in and let it sleep normally.
       Don't shut it down the night before a booking day.


TO TEST IT RIGHT NOW
--------------------
  1. Double-click RunBooking.bat (no admin rights needed)
  2. A black window will briefly appear — this is normal
  3. Chrome will open and the plugin will run
  4. Don't click anything in Chrome while it's running

  The whole process takes about 60-90 seconds. Check your Life Time
  app or email for a booking confirmation.


BOOKING MULTIPLE CLASSES
-------------------------
  Each class has its own folder with its own set of four files.
  To schedule another class, run the Gym Booking Wizard again,
  put the new files in a separate folder, and right-click the new
  RegisterTask.bat once.

  Each class runs independently and won't interfere with the others.


TROUBLESHOOTING
---------------
  "Task could not be registered"
    → Right-click RegisterTask.bat and choose Run as administrator

  "Macro file not found"
    → Make sure all 4 files are in the same folder

  Chrome opens but nothing happens
    → Make sure XModules is installed (Step 2 above)
    → Then double-click RunBooking.bat to try again
    → If it keeps failing, re-run the Wizard and export fresh files

  XModule Status shows red in UIVision settings
    → Re-run the XModules installer from https://ui.vision/rpa/x/download

  PC didn't wake up at booking time
    → Settings → System → Power & Sleep → Additional power settings
      → Change plan settings → Change advanced power settings
      → Sleep → Allow wake timers → set to Enabled

  Booked the wrong class or time
    → Re-run the Gym Booking Wizard and export a fresh set of files

  You're on a work laptop
    → Your company's IT policy may block this. Try on a personal PC.


Generated by the Gym Booking Wizard
`;
}