// scheduler.js
// Generates RunBooking.bat and RegisterTask.bat content from wizard config.
// Called by exporter.js at export time.

/**
 * Generates the RunBooking.bat content that auto-imports the macro then runs it.
 * @param {string} macroName - The filename without extension, e.g. "BookingTemplate"
 * @returns {string} bat file content
 */
function generateRunBookingBat(macroName) {
  return `@echo off
REM ============================================================
REM  RunBooking.bat — Auto-imports and launches UIVision macro
REM  Generated by Life Time Booking Wizard
REM  DO NOT EDIT unless you know what you're doing.
REM ============================================================

SET MACRO_NAME=${macroName}
SET MACRO_FILE=%~dp0${macroName}.json
SET CHROME_PATH=

REM Try default Chrome install locations
IF EXIST "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" (
  SET CHROME_PATH=C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe
)
IF EXIST "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" (
  SET CHROME_PATH=C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe
)

IF "%CHROME_PATH%"=="" (
  echo ERROR: Chrome not found. Please install Google Chrome.
  pause
  exit /b 1
)

IF NOT EXIST "%MACRO_FILE%" (
  echo ERROR: Macro file not found: %MACRO_FILE%
  echo Make sure ${macroName}.json is in the same folder as this bat file.
  pause
  exit /b 1
)

REM Step 1 — Import the macro into UIVision from the local JSON file
echo Importing macro: %MACRO_NAME%
start "" "%CHROME_PATH%" "chrome-extension://gcbalfbdmfieckjlnblleoemohcganoc/popup.html?importmacro=%MACRO_FILE%"

REM Wait for import to complete before launching
timeout /t 5 /nobreak >nul

REM Step 2 — Run the macro
echo Running macro: %MACRO_NAME%
start "" "%CHROME_PATH%" "chrome-extension://gcbalfbdmfieckjlnblleoemohcganoc/popup.html?direct=1&macro=%MACRO_NAME%&close=1&closeRPA=0"

exit /b 0
`;
}

/**
 * Calculates the booking window open date (classDate minus daysAhead).
 * Returns MM/DD/YYYY for schtasks compatibility.
 * @param {number} daysAhead
 * @param {string|null} classDate - YYYY-MM-DD from wizard
 * @returns {string} MM/DD/YYYY
 */
function calcScheduleDate(daysAhead, classDate) {
  let d;
  if (classDate) {
    const [yyyy, mm, dd] = classDate.split('-').map(Number);
    d = new Date(yyyy, mm - 1, dd);     // local midnight — no UTC shift
    d.setDate(d.getDate() - daysAhead); // go back daysAhead days
  } else {
    d = new Date(); // fallback: today
  }
  const mo  = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  const yr  = d.getFullYear();
  return `${mo}/${day}/${yr}`;
}

/**
 * Returns the day-of-week name from a YYYY-MM-DD date string.
 * Uses local date constructor to avoid UTC timezone shifting.
 * e.g. "2026-06-03" → "Wednesday"
 * @param {string|null} classDate
 * @returns {string}
 */
function getDayOfWeek(classDate) {
  if (!classDate) return 'Monday';
  const [yyyy, mm, dd] = classDate.split('-').map(Number);
  const days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
  return days[new Date(yyyy, mm - 1, dd).getDay()];
}

/**
 * Parses a time string like "9:00 AM" or "09:00" into 24-hour HH:MM.
 * @param {string} timeStr
 * @returns {string} HH:MM
 */
function parseTo24Hour(timeStr) {
  const clean = timeStr.trim().toUpperCase();
  const ampm  = clean.includes('AM') ? 'AM' : clean.includes('PM') ? 'PM' : null;
  const parts = clean.replace('AM', '').replace('PM', '').trim().split(':');
  let hours   = parseInt(parts[0], 10);
  const mins  = parts[1] ? parts[1].padStart(2, '0') : '00';
  if (ampm === 'PM' && hours !== 12) hours += 12;
  if (ampm === 'AM' && hours === 12) hours = 0;
  return `${String(hours).padStart(2, '0')}:${mins}`;
}

/**
 * Generates RegisterTask.bat — registers a weekly Windows Scheduled Task
 * AND configures all required system settings automatically.
 * User right-clicks and runs as Administrator once.
 * @param {object} config - wizard state.config or state.config.schedule
 * @param {string} macroName - e.g. "BookingTemplate"
 * @returns {string} bat file content
 */
function generateRegisterTaskBat(config, macroName) {
  const classDate  = config.classDate  || (config.schedule && config.schedule.classDate)  || null;
  const daysAhead  = Number(config.daysAhead  || (config.schedule && config.schedule.daysAhead)  || 7);
  const runTime24  = config.runTime  || (config.schedule && config.schedule.runTime)  || '09:00';

  const schedDate     = calcScheduleDate(daysAhead, classDate);
  const taskName      = `LifeTimeBooking_${macroName.replace(/\s+/g, '_')}`;
  const [mo, day, yr] = schedDate.split('/');
  const isoDateTime   = `${yr}-${mo}-${day}T${runTime24}:00`;
  const dayOfWeek     = getDayOfWeek(classDate);

  return `@echo off
REM ============================================================
REM  RegisterTask.bat — System Setup + Weekly Scheduled Task
REM  RIGHT-CLICK and select "Run as administrator"
REM  You only need to do this ONCE.
REM ============================================================

SET TASK_NAME=${taskName}
SET BAT_PATH=%~dp0RunBooking.bat
SET XML_PATH=%~dp0task.xml

echo(
echo ============================================================
echo  STEP 1 — Configuring system settings for reliable automation
echo ============================================================
echo(

REM Enable wake timers on AC power and battery
powercfg /setacvalueindex SCHEME_CURRENT SUB_SLEEP RTCWAKE 1
powercfg /setdcvalueindex SCHEME_CURRENT SUB_SLEEP RTCWAKE 1
powercfg /setactive SCHEME_CURRENT
echo [OK] Wake timers enabled

REM Set sleep timeout to 30 minutes so PC stays awake during macro
powercfg /change standby-timeout-ac 30
powercfg /change standby-timeout-dc 30
echo [OK] Sleep timeout set to 30 minutes minimum

REM Disable fast startup (can interfere with scheduled wake)
reg add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Power" /v HiberbootEnabled /t REG_DWORD /d 0 /f >nul 2>&1
echo [OK] Fast startup disabled

REM Allow UIVision extension to access local file URLs
reg add "HKLM\\SOFTWARE\\Policies\\Google\\Chrome\\ExtensionSettings\\gcbalfbdmfieckjlnblleoemohcganoc" /v "file_url_navigation_allowed" /t REG_DWORD /d 1 /f >nul 2>&1
echo [OK] UIVision file access configured

REM Check if UIVision storage folder exists (confirms UIVision is installed)
SET UIVISION_DIR=%USERPROFILE%\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\File System
IF EXIST "%UIVISION_DIR%" (
  echo [OK] UIVision installation detected
) ELSE (
  echo [!!] WARNING: UIVision folder not found.
  echo      Make sure UIVision is installed in Chrome before running the macro.
  echo      Install from: https://chrome.google.com/webstore/detail/uivision/gcbalfbdmfieckjlnblleoemohcganoc
)

REM Warn if domain-joined (corporate PCs may force screen lock)
for /f "tokens=2 delims==" %%a in ('wmic computersystem get partofdomain /value 2^>nul') do set DOMAIN=%%a
if /i "%DOMAIN%"=="TRUE" (
  echo(
  echo [!!] WARNING: This PC is joined to a corporate domain.
  echo      Your IT policy may lock the screen and block the macro.
  echo      Contact your IT department if bookings fail silently.
)

echo(
echo ============================================================
echo  STEP 2 — Registering weekly scheduled task
echo ============================================================
echo(
echo Task name   : %TASK_NAME%
echo First run   : ${isoDateTime}
echo Repeats     : Every ${dayOfWeek} at ${runTime24}
echo Bat file    : %BAT_PATH%
echo(

REM Write the task XML file
(
echo ^<?xml version="1.0" encoding="UTF-16"?^>
echo ^<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task"^>
echo   ^<Triggers^>
echo     ^<CalendarTrigger^>
echo       ^<StartBoundary^>${isoDateTime}^</StartBoundary^>
echo       ^<Enabled^>true^</Enabled^>
echo       ^<ScheduleByWeek^>
echo         ^<WeeksInterval^>1^</WeeksInterval^>
echo         ^<DaysOfWeek^>
echo           ^<${dayOfWeek}/^>
echo         ^</DaysOfWeek^>
echo       ^</ScheduleByWeek^>
echo     ^</CalendarTrigger^>
echo   ^</Triggers^>
echo   ^<Settings^>
echo     ^<StartWhenAvailable^>true^</StartWhenAvailable^>
echo     ^<WakeToRun^>true^</WakeToRun^>
echo     ^<DisallowStartIfOnBatteries^>false^</DisallowStartIfOnBatteries^>
echo     ^<StopIfGoingOnBatteries^>false^</StopIfGoingOnBatteries^>
echo     ^<ExecutionTimeLimit^>PT1H^</ExecutionTimeLimit^>
echo     ^<MultipleInstancesPolicy^>IgnoreNew^</MultipleInstancesPolicy^>
echo   ^</Settings^>
echo   ^<Actions Context="Author"^>
echo     ^<Exec^>
echo       ^<Command^>"%BAT_PATH%"^</Command^>
echo     ^</Exec^>
echo   ^</Actions^>
echo   ^<Principals^>
echo     ^<Principal id="Author"^>
echo       ^<LogonType^>InteractiveToken^</LogonType^>
echo       ^<RunLevel^>HighestAvailable^</RunLevel^>
echo     ^</Principal^>
echo   ^</Principals^>
echo ^</Task^>
) > "%XML_PATH%"

schtasks /create /tn "%TASK_NAME%" /xml "%XML_PATH%" /f

IF %ERRORLEVEL% EQU 0 (
  echo(
  echo ============================================================
  echo  SUCCESS! Everything is configured and scheduled.
  echo ============================================================
  echo(
  echo Task      : %TASK_NAME%
  echo First run : ${isoDateTime}
  echo Repeats   : Every ${dayOfWeek} at ${runTime24}
  echo(
  echo To run RIGHT NOW for testing, double-click RunBooking.bat
  echo(
  echo IMPORTANT: PC must be ON or in SLEEP mode at booking time.
  echo            Hibernate and Shutdown will prevent the wake.
  echo(
  echo If wake-from-sleep does not work, check Windows power settings:
  echo   Settings - System - Power and Sleep - Additional power settings
  echo   Change plan settings - Change advanced power settings
  echo   Sleep - Allow wake timers - set to Enabled
) ELSE (
  echo(
  echo ERROR: Scheduled task could not be registered.
  echo Did you right-click and choose "Run as administrator"?
)

REM Clean up temp XML
IF EXIST "%XML_PATH%" DEL "%XML_PATH%"

echo(
pause
`;
}

/**
 * Generates a plain-English README_BOOKING.txt for non-techie users.
 * @param {object} config - wizard state.config or state.config.schedule
 * @param {string} macroName
 * @returns {string}
 */
function generateReadme(config, macroName) {
  const classDate = config.classDate || (config.schedule && config.schedule.classDate) || null;
  const daysAhead = Number(config.daysAhead || (config.schedule && config.schedule.daysAhead) || 7);
  const runTime24 = config.runTime || (config.schedule && config.schedule.runTime) || '09:00';
  const schedDate = calcScheduleDate(daysAhead, classDate);
  const dayOfWeek = getDayOfWeek(classDate);

  return `GYM BOOKING AUTOMATION — SETUP INSTRUCTIONS
===================================================

Files included in this folder:
  • ${macroName}.json       → Your booking macro (auto-loaded, do not move)
  • RunBooking.bat          → Runs your booking macro (double-click to test)
  • RegisterTask.bat        → Configures your PC + schedules the task
  • README_BOOKING.txt      → This file

IMPORTANT: Keep all four files in the same folder at all times.
           Moving or renaming them will break the automation.

BEFORE YOU START — ONE-TIME MANUAL STEPS
-----------------------------------------
1. Install UIVision from the Chrome Web Store:
   https://chrome.google.com/webstore/detail/uivision/gcbalfbdmfieckjlnblleoemohcganoc

2. Open UIVision once after installing, then close it.
   (This creates the storage folders it needs.)

3. Disable screen lock after sleep (IMPORTANT):
   Settings → Accounts → Sign-in options
   → "Require sign-in" → set to "Never"
   (If the screen locks, Chrome cannot complete the booking.)

That's it — RunBooking.bat handles everything else automatically,
including loading the macro into UIVision every time it runs.

STEP 1 — Run the setup (do this ONCE)
---------------------------------------
  1. Right-click RegisterTask.bat
  2. Select "Run as administrator"
  3. You should see: SUCCESS! Everything is configured and scheduled.

  The task will run automatically every ${dayOfWeek} at ${runTime24}.

STEP 2 — Leave your PC on or in Sleep mode
-------------------------------------------
  First scheduled run:
    Date : ${schedDate}
    Time : ${runTime24}
  Repeats every ${dayOfWeek} at ${runTime24} automatically.

  Sleep mode = OK  ✓
  Hibernate   = Will NOT wake  ✗
  Shutdown    = Will NOT wake  ✗

TO TEST RIGHT NOW
-----------------
  Double-click RunBooking.bat — no admin rights needed.
  It will import the macro and run it immediately.

RUNNING MULTIPLE CLASSES
-------------------------
  Each class has its own folder with its own set of files.
  Right-click each RegisterTask.bat once to schedule each class.
  They run independently and do not interfere with each other.

TROUBLESHOOTING
---------------
  • "Task could not be registered"  → Right-click → Run as administrator
  • "Macro file not found"          → Make sure all 4 files are in the same folder
  • Chrome opens but macro fails    → Re-run the wizard and export fresh files
  • PC didn't wake from sleep       → Settings → Power → Allow wake timers → Enabled
  • Wrong schedule?                 → Re-run the wizard and export fresh files
  • Corporate/work PC issues        → Your IT policy may block automation

Generated by Gym Booking Wizard
`;
}